package com.commlink.agent.model;
// Generated Sep 18, 2019 3:24:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private int id;
     private Product product;
     private boolean isDeleted;
     private String createdBy;
     private Date creationDate;
     private String modifiedBy;
     private Date modificationDate;
     private String accNo;
     private String productCode;
     private String description;
     private Short status;
     private Date openOn;
     private Date closeOn;
     private Date freezeOn;
     private Integer associatedAgentAcc;
     private Integer makerId;
     private Integer checkerId;
     private Integer operatorType;
     private String name;
     private Integer accountType;
     private Set transactionsForSrcAccId = new HashSet(0);
     private Set accountCustomers = new HashSet(0);
     private Set transactionsForAgentAccId = new HashSet(0);
     private Set transactionsForDestAccId = new HashSet(0);
     private Set transactionDetails = new HashSet(0);

    public Account() {
    }

	
    public Account(int id, boolean isDeleted, String accNo, String productCode) {
        this.id = id;
        this.isDeleted = isDeleted;
        this.accNo = accNo;
        this.productCode = productCode;
    }
    public Account(int id, Product product, boolean isDeleted, String createdBy, Date creationDate, String modifiedBy, Date modificationDate, String accNo, String productCode, String description, Short status, Date openOn, Date closeOn, Date freezeOn, Integer associatedAgentAcc, Integer makerId, Integer checkerId, Integer operatorType, String name, Integer accountType, Set transactionsForSrcAccId, Set accountCustomers, Set transactionsForAgentAccId, Set transactionsForDestAccId, Set transactionDetails) {
       this.id = id;
       this.product = product;
       this.isDeleted = isDeleted;
       this.createdBy = createdBy;
       this.creationDate = creationDate;
       this.modifiedBy = modifiedBy;
       this.modificationDate = modificationDate;
       this.accNo = accNo;
       this.productCode = productCode;
       this.description = description;
       this.status = status;
       this.openOn = openOn;
       this.closeOn = closeOn;
       this.freezeOn = freezeOn;
       this.associatedAgentAcc = associatedAgentAcc;
       this.makerId = makerId;
       this.checkerId = checkerId;
       this.operatorType = operatorType;
       this.name = name;
       this.accountType = accountType;
       this.transactionsForSrcAccId = transactionsForSrcAccId;
       this.accountCustomers = accountCustomers;
       this.transactionsForAgentAccId = transactionsForAgentAccId;
       this.transactionsForDestAccId = transactionsForDestAccId;
       this.transactionDetails = transactionDetails;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }
    public String getAccNo() {
        return this.accNo;
    }
    
    public void setAccNo(String accNo) {
        this.accNo = accNo;
    }
    public String getProductCode() {
        return this.productCode;
    }
    
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Short getStatus() {
        return this.status;
    }
    
    public void setStatus(Short status) {
        this.status = status;
    }
    public Date getOpenOn() {
        return this.openOn;
    }
    
    public void setOpenOn(Date openOn) {
        this.openOn = openOn;
    }
    public Date getCloseOn() {
        return this.closeOn;
    }
    
    public void setCloseOn(Date closeOn) {
        this.closeOn = closeOn;
    }
    public Date getFreezeOn() {
        return this.freezeOn;
    }
    
    public void setFreezeOn(Date freezeOn) {
        this.freezeOn = freezeOn;
    }
    public Integer getAssociatedAgentAcc() {
        return this.associatedAgentAcc;
    }
    
    public void setAssociatedAgentAcc(Integer associatedAgentAcc) {
        this.associatedAgentAcc = associatedAgentAcc;
    }
    public Integer getMakerId() {
        return this.makerId;
    }
    
    public void setMakerId(Integer makerId) {
        this.makerId = makerId;
    }
    public Integer getCheckerId() {
        return this.checkerId;
    }
    
    public void setCheckerId(Integer checkerId) {
        this.checkerId = checkerId;
    }
    public Integer getOperatorType() {
        return this.operatorType;
    }
    
    public void setOperatorType(Integer operatorType) {
        this.operatorType = operatorType;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(Integer accountType) {
        this.accountType = accountType;
    }
    public Set getTransactionsForSrcAccId() {
        return this.transactionsForSrcAccId;
    }
    
    public void setTransactionsForSrcAccId(Set transactionsForSrcAccId) {
        this.transactionsForSrcAccId = transactionsForSrcAccId;
    }
    public Set getAccountCustomers() {
        return this.accountCustomers;
    }
    
    public void setAccountCustomers(Set accountCustomers) {
        this.accountCustomers = accountCustomers;
    }
    public Set getTransactionsForAgentAccId() {
        return this.transactionsForAgentAccId;
    }
    
    public void setTransactionsForAgentAccId(Set transactionsForAgentAccId) {
        this.transactionsForAgentAccId = transactionsForAgentAccId;
    }
    public Set getTransactionsForDestAccId() {
        return this.transactionsForDestAccId;
    }
    
    public void setTransactionsForDestAccId(Set transactionsForDestAccId) {
        this.transactionsForDestAccId = transactionsForDestAccId;
    }
    public Set getTransactionDetails() {
        return this.transactionDetails;
    }
    
    public void setTransactionDetails(Set transactionDetails) {
        this.transactionDetails = transactionDetails;
    }




}


