package com.commlink.agent.model;
// Generated Sep 18, 2019 3:24:34 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * AccountBalance generated by hbm2java
 */
public class AccountBalance  implements java.io.Serializable {


     private int id;
     private BigDecimal amount;
     private Date updatedAt;
     private Integer balanceType;
     private Integer accountId;
     private boolean isDeleted;
     private String createdBy;
     private Date creationDate;
     private String modifiedBy;
     private Date modificationDate;

    public AccountBalance() {
    }

	
    public AccountBalance(int id, boolean isDeleted) {
        this.id = id;
        this.isDeleted = isDeleted;
    }
    public AccountBalance(int id, BigDecimal amount, Date updatedAt, Integer balanceType, Integer accountId, boolean isDeleted, String createdBy, Date creationDate, String modifiedBy, Date modificationDate) {
       this.id = id;
       this.amount = amount;
       this.updatedAt = updatedAt;
       this.balanceType = balanceType;
       this.accountId = accountId;
       this.isDeleted = isDeleted;
       this.createdBy = createdBy;
       this.creationDate = creationDate;
       this.modifiedBy = modifiedBy;
       this.modificationDate = modificationDate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Integer getBalanceType() {
        return this.balanceType;
    }
    
    public void setBalanceType(Integer balanceType) {
        this.balanceType = balanceType;
    }
    public Integer getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }




}


