package com.commlink.agent.model;
// Generated Sep 18, 2019 4:58:14 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AccountCustomer generated by hbm2java
 */
@Entity
@Table(name="ACCOUNT_CUSTOMER"
    ,schema="AGENT"
)
public class AccountCustomer  implements java.io.Serializable {


     private int id;
     private Account account;
     private Customer customer;

    public AccountCustomer() {
    }

	
    public AccountCustomer(int id) {
        this.id = id;
    }
    public AccountCustomer(int id, Account account, Customer customer) {
       this.id = id;
       this.account = account;
       this.customer = customer;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=8, scale=0)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ACCOUNT_ID")
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CUSTOMER_ID")
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }




}


