package com.commlink.agent.model;
// Generated Sep 18, 2019 3:24:34 PM by Hibernate Tools 4.3.1



/**
 * AccountCustomer generated by hbm2java
 */
public class AccountCustomer  implements java.io.Serializable {


     private int id;
     private Account account;
     private Customer customer;

    public AccountCustomer() {
    }

	
    public AccountCustomer(int id) {
        this.id = id;
    }
    public AccountCustomer(int id, Account account, Customer customer) {
       this.id = id;
       this.account = account;
       this.customer = customer;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }




}


