package com.commlink.agent.model;
// Generated Sep 18, 2019 3:24:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AgentDetail generated by hbm2java
 */
public class AgentDetail  implements java.io.Serializable {


     private int id;
     private Customer customer;
     private String agentCode;
     private Short status;
     private Boolean isDeleted;
     private String createdBy;
     private Date creationDate;
     private String modifiedBy;
     private Date modificationDate;
     private Set commissions = new HashSet(0);

    public AgentDetail() {
    }

	
    public AgentDetail(int id, Customer customer, String agentCode) {
        this.id = id;
        this.customer = customer;
        this.agentCode = agentCode;
    }
    public AgentDetail(int id, Customer customer, String agentCode, Short status, Boolean isDeleted, String createdBy, Date creationDate, String modifiedBy, Date modificationDate, Set commissions) {
       this.id = id;
       this.customer = customer;
       this.agentCode = agentCode;
       this.status = status;
       this.isDeleted = isDeleted;
       this.createdBy = createdBy;
       this.creationDate = creationDate;
       this.modifiedBy = modifiedBy;
       this.modificationDate = modificationDate;
       this.commissions = commissions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public String getAgentCode() {
        return this.agentCode;
    }
    
    public void setAgentCode(String agentCode) {
        this.agentCode = agentCode;
    }
    public Short getStatus() {
        return this.status;
    }
    
    public void setStatus(Short status) {
        this.status = status;
    }
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }
    public Set getCommissions() {
        return this.commissions;
    }
    
    public void setCommissions(Set commissions) {
        this.commissions = commissions;
    }




}


