package com.commlink.agent.model;
// Generated Sep 25, 2019 11:25:45 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AgentCommissionProfile generated by hbm2java
 */
@Entity
@Table(name="AGENT_COMMISSION_PROFILE"
    ,schema="AGENT"
)
public class AgentCommissionProfile  implements java.io.Serializable {


     private int id;
     private String name;
     private String createdBy;
     private Date creationDate;
     private String modifiedBy;
     private Date modifiedDate;
     private Set<AgentDetail> agentDetails = new HashSet<AgentDetail>(0);
     private Set<CommissionProfile> commissionProfiles = new HashSet<CommissionProfile>(0);

    public AgentCommissionProfile() {
    }

	
    public AgentCommissionProfile(int id) {
        this.id = id;
    }
    public AgentCommissionProfile(int id, String name, String createdBy, Date creationDate, String modifiedBy, Date modifiedDate, Set<AgentDetail> agentDetails, Set<CommissionProfile> commissionProfiles) {
       this.id = id;
       this.name = name;
       this.createdBy = createdBy;
       this.creationDate = creationDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.agentDetails = agentDetails;
       this.commissionProfiles = commissionProfiles;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=8, scale=0)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="NAME", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="CREATED_BY", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATION_DATE")
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    
    @Column(name="MODIFIED_BY", length=20)
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED_DATE")
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="agentCommissionProfile")
    public Set<AgentDetail> getAgentDetails() {
        return this.agentDetails;
    }
    
    public void setAgentDetails(Set<AgentDetail> agentDetails) {
        this.agentDetails = agentDetails;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="agentCommissionProfile")
    public Set<CommissionProfile> getCommissionProfiles() {
        return this.commissionProfiles;
    }
    
    public void setCommissionProfiles(Set<CommissionProfile> commissionProfiles) {
        this.commissionProfiles = commissionProfiles;
    }




}


