package com.commlink.agent.model;
// Generated Sep 18, 2019 3:24:34 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Commission generated by hbm2java
 */
public class Commission  implements java.io.Serializable {


     private int id;
     private AgentDetail agentDetail;
     private TransactionType transactionType;
     private Boolean isAmountWise;
     private BigDecimal criteria;
     private BigDecimal rangeLowerLimit;
     private BigDecimal rangeUpperLimit;
     private boolean isDeleted;
     private String createdBy;
     private Date creationDate;
     private String modifiedBy;
     private Date modificationDate;
     private Boolean isPercentage;
     private String bankAccount;
     private Double agentPortion;
     private double bankPortion;
     private Double otherPortion;
     private String otherAccount;

    public Commission() {
    }

	
    public Commission(int id, AgentDetail agentDetail, TransactionType transactionType, boolean isDeleted, String bankAccount, double bankPortion) {
        this.id = id;
        this.agentDetail = agentDetail;
        this.transactionType = transactionType;
        this.isDeleted = isDeleted;
        this.bankAccount = bankAccount;
        this.bankPortion = bankPortion;
    }
    public Commission(int id, AgentDetail agentDetail, TransactionType transactionType, Boolean isAmountWise, BigDecimal criteria, BigDecimal rangeLowerLimit, BigDecimal rangeUpperLimit, boolean isDeleted, String createdBy, Date creationDate, String modifiedBy, Date modificationDate, Boolean isPercentage, String bankAccount, Double agentPortion, double bankPortion, Double otherPortion, String otherAccount) {
       this.id = id;
       this.agentDetail = agentDetail;
       this.transactionType = transactionType;
       this.isAmountWise = isAmountWise;
       this.criteria = criteria;
       this.rangeLowerLimit = rangeLowerLimit;
       this.rangeUpperLimit = rangeUpperLimit;
       this.isDeleted = isDeleted;
       this.createdBy = createdBy;
       this.creationDate = creationDate;
       this.modifiedBy = modifiedBy;
       this.modificationDate = modificationDate;
       this.isPercentage = isPercentage;
       this.bankAccount = bankAccount;
       this.agentPortion = agentPortion;
       this.bankPortion = bankPortion;
       this.otherPortion = otherPortion;
       this.otherAccount = otherAccount;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public AgentDetail getAgentDetail() {
        return this.agentDetail;
    }
    
    public void setAgentDetail(AgentDetail agentDetail) {
        this.agentDetail = agentDetail;
    }
    public TransactionType getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(TransactionType transactionType) {
        this.transactionType = transactionType;
    }
    public Boolean getIsAmountWise() {
        return this.isAmountWise;
    }
    
    public void setIsAmountWise(Boolean isAmountWise) {
        this.isAmountWise = isAmountWise;
    }
    public BigDecimal getCriteria() {
        return this.criteria;
    }
    
    public void setCriteria(BigDecimal criteria) {
        this.criteria = criteria;
    }
    public BigDecimal getRangeLowerLimit() {
        return this.rangeLowerLimit;
    }
    
    public void setRangeLowerLimit(BigDecimal rangeLowerLimit) {
        this.rangeLowerLimit = rangeLowerLimit;
    }
    public BigDecimal getRangeUpperLimit() {
        return this.rangeUpperLimit;
    }
    
    public void setRangeUpperLimit(BigDecimal rangeUpperLimit) {
        this.rangeUpperLimit = rangeUpperLimit;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }
    public Boolean getIsPercentage() {
        return this.isPercentage;
    }
    
    public void setIsPercentage(Boolean isPercentage) {
        this.isPercentage = isPercentage;
    }
    public String getBankAccount() {
        return this.bankAccount;
    }
    
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount;
    }
    public Double getAgentPortion() {
        return this.agentPortion;
    }
    
    public void setAgentPortion(Double agentPortion) {
        this.agentPortion = agentPortion;
    }
    public double getBankPortion() {
        return this.bankPortion;
    }
    
    public void setBankPortion(double bankPortion) {
        this.bankPortion = bankPortion;
    }
    public Double getOtherPortion() {
        return this.otherPortion;
    }
    
    public void setOtherPortion(Double otherPortion) {
        this.otherPortion = otherPortion;
    }
    public String getOtherAccount() {
        return this.otherAccount;
    }
    
    public void setOtherAccount(String otherAccount) {
        this.otherAccount = otherAccount;
    }




}


