package com.commlink.agent.model;
// Generated Sep 25, 2019 11:25:45 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CommissionProfile generated by hbm2java
 */
@Entity
@Table(name="COMMISSION_PROFILE"
    ,schema="AGENT"
)
public class CommissionProfile  implements java.io.Serializable {


     private int id;
     private Commission commission;
     private AgentCommissionProfile agentCommissionProfile;

    public CommissionProfile() {
    }

    public CommissionProfile(int id, Commission commission, AgentCommissionProfile agentCommissionProfile) {
       this.id = id;
       this.commission = commission;
       this.agentCommissionProfile = agentCommissionProfile;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=8, scale=0)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COMMISSION_ID", nullable=false)
    public Commission getCommission() {
        return this.commission;
    }
    
    public void setCommission(Commission commission) {
        this.commission = commission;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AGENT_COMMISSION_PROFILE_ID", nullable=false)
    public AgentCommissionProfile getAgentCommissionProfile() {
        return this.agentCommissionProfile;
    }
    
    public void setAgentCommissionProfile(AgentCommissionProfile agentCommissionProfile) {
        this.agentCommissionProfile = agentCommissionProfile;
    }




}


