package com.commlink.agent.model;
// Generated Sep 25, 2019 11:25:45 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commission generated by hbm2java
 */
@Entity
@Table(name="COMMISSION"
    ,schema="AGENT"
)
public class Commission  implements java.io.Serializable {


     private int id;
     private Product product;
     private TransactionType transactionType;
     private Range range;
     private Boolean isAmountWise;
     private Integer criteria;
     private boolean isDeleted;
     private String createdBy;
     private Date creationDate;
     private String modifiedBy;
     private Date modificationDate;
     private Boolean isPercentage;
     private Double agentPortion;
     private Double bankPortion;
     private Date startDate;
     private Date endDate;
     private Set<CommissionProfile> commissionProfiles = new HashSet<CommissionProfile>(0);

    public Commission() {
    }

	
    public Commission(int id, TransactionType transactionType, boolean isDeleted) {
        this.id = id;
        this.transactionType = transactionType;
        this.isDeleted = isDeleted;
    }
    public Commission(int id, Product product, TransactionType transactionType, Range range, Boolean isAmountWise, Integer criteria, boolean isDeleted, String createdBy, Date creationDate, String modifiedBy, Date modificationDate, Boolean isPercentage, Double agentPortion, Double bankPortion, Date startDate, Date endDate, Set<CommissionProfile> commissionProfiles) {
       this.id = id;
       this.product = product;
       this.transactionType = transactionType;
       this.range = range;
       this.isAmountWise = isAmountWise;
       this.criteria = criteria;
       this.isDeleted = isDeleted;
       this.createdBy = createdBy;
       this.creationDate = creationDate;
       this.modifiedBy = modifiedBy;
       this.modificationDate = modificationDate;
       this.isPercentage = isPercentage;
       this.agentPortion = agentPortion;
       this.bankPortion = bankPortion;
       this.startDate = startDate;
       this.endDate = endDate;
       this.commissionProfiles = commissionProfiles;
    }
   
    @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=8, scale=0)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUCT_ID")
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TRANSACTION_TYPE_ID", nullable=false)
    public TransactionType getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(TransactionType transactionType) {
        this.transactionType = transactionType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RANGE_ID")
    public Range getRange() {
        return this.range;
    }
    
    public void setRange(Range range) {
        this.range = range;
    }

    
    @Column(name="IS_AMOUNT_WISE", precision=1, scale=0)
    public Boolean getIsAmountWise() {
        return this.isAmountWise;
    }
    
    public void setIsAmountWise(Boolean isAmountWise) {
        this.isAmountWise = isAmountWise;
    }

    
    @Column(name="CRITERIA", precision=8, scale=0)
    public Integer getCriteria() {
        return this.criteria;
    }
    
    public void setCriteria(Integer criteria) {
        this.criteria = criteria;
    }

    
    @Column(name="IS_DELETED", nullable=false, precision=1, scale=0)
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    
    @Column(name="CREATED_BY", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATION_DATE")
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    
    @Column(name="MODIFIED_BY", length=20)
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFICATION_DATE")
    public Date getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }

    
    @Column(name="IS_PERCENTAGE", precision=1, scale=0)
    public Boolean getIsPercentage() {
        return this.isPercentage;
    }
    
    public void setIsPercentage(Boolean isPercentage) {
        this.isPercentage = isPercentage;
    }

    
    @Column(name="AGENT_PORTION", precision=8, scale=0)
    public Double getAgentPortion() {
        return this.agentPortion;
    }
    
    public void setAgentPortion(Double agentPortion) {
        this.agentPortion = agentPortion;
    }

    
    @Column(name="BANK_PORTION", precision=8, scale=0)
    public Double getBankPortion() {
        return this.bankPortion;
    }
    
    public void setBankPortion(Double bankPortion) {
        this.bankPortion = bankPortion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="START_DATE")
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="END_DATE")
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="commission")
    public Set<CommissionProfile> getCommissionProfiles() {
        return this.commissionProfiles;
    }
    
    public void setCommissionProfiles(Set<CommissionProfile> commissionProfiles) {
        this.commissionProfiles = commissionProfiles;
    }




}


