package com.commlink.agent.model;
// Generated Sep 18, 2019 3:24:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CustomerProduct generated by hbm2java
 */
public class CustomerProduct  implements java.io.Serializable {


     private int id;
     private Product product;
     private Customer customer;
     private Short type;
     private Date dateTime;
     private Short status;

    public CustomerProduct() {
    }

	
    public CustomerProduct(int id) {
        this.id = id;
    }
    public CustomerProduct(int id, Product product, Customer customer, Short type, Date dateTime, Short status) {
       this.id = id;
       this.product = product;
       this.customer = customer;
       this.type = type;
       this.dateTime = dateTime;
       this.status = status;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Short getType() {
        return this.type;
    }
    
    public void setType(Short type) {
        this.type = type;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public Short getStatus() {
        return this.status;
    }
    
    public void setStatus(Short status) {
        this.status = status;
    }




}


