package com.commlink.agent.model;
// Generated Sep 18, 2019 3:24:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private int id;
     private Organization organization;
     private Division divisionByPermanentDivisionId;
     private Division divisionByPresentDivisionId;
     private District districtByPresentDistrictId;
     private District districtByPermanentDistrictId;
     private Upazila upazilaByPresentUpazilaId;
     private Upazila upazilaByPermanentUpazilaId;
     private String firstName;
     private String middleName;
     private String lastName;
     private Date dob;
     private boolean isDeleted;
     private String createdBy;
     private Date creationDate;
     private String modifiedBy;
     private Date modificationDate;
     private String homeBranch;
     private Integer status;
     private String fatherName;
     private String motherName;
     private String spouseName;
     private String tin;
     private String nid;
     private String employeeId;
     private String email;
     private String phone;
     private String sourceOfFund;
     private String presentPostCode;
     private String permanentPostCode;
     private String presentVillage;
     private String nationality;
     private String occupation;
     private String designation;
     private String monthlyIncome;
     private String photoUrl;
     private String signatureUrl;
     private Integer currency;
     private Integer gender;
     private Integer maritalStatus;
     private Integer residenceStatus;
     private Set userInfos = new HashSet(0);
     private Set agentDetails = new HashSet(0);
     private Set customerProducts = new HashSet(0);
     private Set accountCustomers = new HashSet(0);

    public Customer() {
    }

	
    public Customer(int id, String firstName, String lastName, boolean isDeleted) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.isDeleted = isDeleted;
    }
    public Customer(int id, Organization organization, Division divisionByPermanentDivisionId, Division divisionByPresentDivisionId, District districtByPresentDistrictId, District districtByPermanentDistrictId, Upazila upazilaByPresentUpazilaId, Upazila upazilaByPermanentUpazilaId, String firstName, String middleName, String lastName, Date dob, boolean isDeleted, String createdBy, Date creationDate, String modifiedBy, Date modificationDate, String homeBranch, Integer status, String fatherName, String motherName, String spouseName, String tin, String nid, String employeeId, String email, String phone, String sourceOfFund, String presentPostCode, String permanentPostCode, String presentVillage, String nationality, String occupation, String designation, String monthlyIncome, String photoUrl, String signatureUrl, Integer currency, Integer gender, Integer maritalStatus, Integer residenceStatus, Set userInfos, Set agentDetails, Set customerProducts, Set accountCustomers) {
       this.id = id;
       this.organization = organization;
       this.divisionByPermanentDivisionId = divisionByPermanentDivisionId;
       this.divisionByPresentDivisionId = divisionByPresentDivisionId;
       this.districtByPresentDistrictId = districtByPresentDistrictId;
       this.districtByPermanentDistrictId = districtByPermanentDistrictId;
       this.upazilaByPresentUpazilaId = upazilaByPresentUpazilaId;
       this.upazilaByPermanentUpazilaId = upazilaByPermanentUpazilaId;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.dob = dob;
       this.isDeleted = isDeleted;
       this.createdBy = createdBy;
       this.creationDate = creationDate;
       this.modifiedBy = modifiedBy;
       this.modificationDate = modificationDate;
       this.homeBranch = homeBranch;
       this.status = status;
       this.fatherName = fatherName;
       this.motherName = motherName;
       this.spouseName = spouseName;
       this.tin = tin;
       this.nid = nid;
       this.employeeId = employeeId;
       this.email = email;
       this.phone = phone;
       this.sourceOfFund = sourceOfFund;
       this.presentPostCode = presentPostCode;
       this.permanentPostCode = permanentPostCode;
       this.presentVillage = presentVillage;
       this.nationality = nationality;
       this.occupation = occupation;
       this.designation = designation;
       this.monthlyIncome = monthlyIncome;
       this.photoUrl = photoUrl;
       this.signatureUrl = signatureUrl;
       this.currency = currency;
       this.gender = gender;
       this.maritalStatus = maritalStatus;
       this.residenceStatus = residenceStatus;
       this.userInfos = userInfos;
       this.agentDetails = agentDetails;
       this.customerProducts = customerProducts;
       this.accountCustomers = accountCustomers;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Organization getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(Organization organization) {
        this.organization = organization;
    }
    public Division getDivisionByPermanentDivisionId() {
        return this.divisionByPermanentDivisionId;
    }
    
    public void setDivisionByPermanentDivisionId(Division divisionByPermanentDivisionId) {
        this.divisionByPermanentDivisionId = divisionByPermanentDivisionId;
    }
    public Division getDivisionByPresentDivisionId() {
        return this.divisionByPresentDivisionId;
    }
    
    public void setDivisionByPresentDivisionId(Division divisionByPresentDivisionId) {
        this.divisionByPresentDivisionId = divisionByPresentDivisionId;
    }
    public District getDistrictByPresentDistrictId() {
        return this.districtByPresentDistrictId;
    }
    
    public void setDistrictByPresentDistrictId(District districtByPresentDistrictId) {
        this.districtByPresentDistrictId = districtByPresentDistrictId;
    }
    public District getDistrictByPermanentDistrictId() {
        return this.districtByPermanentDistrictId;
    }
    
    public void setDistrictByPermanentDistrictId(District districtByPermanentDistrictId) {
        this.districtByPermanentDistrictId = districtByPermanentDistrictId;
    }
    public Upazila getUpazilaByPresentUpazilaId() {
        return this.upazilaByPresentUpazilaId;
    }
    
    public void setUpazilaByPresentUpazilaId(Upazila upazilaByPresentUpazilaId) {
        this.upazilaByPresentUpazilaId = upazilaByPresentUpazilaId;
    }
    public Upazila getUpazilaByPermanentUpazilaId() {
        return this.upazilaByPermanentUpazilaId;
    }
    
    public void setUpazilaByPermanentUpazilaId(Upazila upazilaByPermanentUpazilaId) {
        this.upazilaByPermanentUpazilaId = upazilaByPermanentUpazilaId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }
    public String getHomeBranch() {
        return this.homeBranch;
    }
    
    public void setHomeBranch(String homeBranch) {
        this.homeBranch = homeBranch;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getFatherName() {
        return this.fatherName;
    }
    
    public void setFatherName(String fatherName) {
        this.fatherName = fatherName;
    }
    public String getMotherName() {
        return this.motherName;
    }
    
    public void setMotherName(String motherName) {
        this.motherName = motherName;
    }
    public String getSpouseName() {
        return this.spouseName;
    }
    
    public void setSpouseName(String spouseName) {
        this.spouseName = spouseName;
    }
    public String getTin() {
        return this.tin;
    }
    
    public void setTin(String tin) {
        this.tin = tin;
    }
    public String getNid() {
        return this.nid;
    }
    
    public void setNid(String nid) {
        this.nid = nid;
    }
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getSourceOfFund() {
        return this.sourceOfFund;
    }
    
    public void setSourceOfFund(String sourceOfFund) {
        this.sourceOfFund = sourceOfFund;
    }
    public String getPresentPostCode() {
        return this.presentPostCode;
    }
    
    public void setPresentPostCode(String presentPostCode) {
        this.presentPostCode = presentPostCode;
    }
    public String getPermanentPostCode() {
        return this.permanentPostCode;
    }
    
    public void setPermanentPostCode(String permanentPostCode) {
        this.permanentPostCode = permanentPostCode;
    }
    public String getPresentVillage() {
        return this.presentVillage;
    }
    
    public void setPresentVillage(String presentVillage) {
        this.presentVillage = presentVillage;
    }
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }
    public String getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public String getMonthlyIncome() {
        return this.monthlyIncome;
    }
    
    public void setMonthlyIncome(String monthlyIncome) {
        this.monthlyIncome = monthlyIncome;
    }
    public String getPhotoUrl() {
        return this.photoUrl;
    }
    
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl;
    }
    public String getSignatureUrl() {
        return this.signatureUrl;
    }
    
    public void setSignatureUrl(String signatureUrl) {
        this.signatureUrl = signatureUrl;
    }
    public Integer getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(Integer currency) {
        this.currency = currency;
    }
    public Integer getGender() {
        return this.gender;
    }
    
    public void setGender(Integer gender) {
        this.gender = gender;
    }
    public Integer getMaritalStatus() {
        return this.maritalStatus;
    }
    
    public void setMaritalStatus(Integer maritalStatus) {
        this.maritalStatus = maritalStatus;
    }
    public Integer getResidenceStatus() {
        return this.residenceStatus;
    }
    
    public void setResidenceStatus(Integer residenceStatus) {
        this.residenceStatus = residenceStatus;
    }
    public Set getUserInfos() {
        return this.userInfos;
    }
    
    public void setUserInfos(Set userInfos) {
        this.userInfos = userInfos;
    }
    public Set getAgentDetails() {
        return this.agentDetails;
    }
    
    public void setAgentDetails(Set agentDetails) {
        this.agentDetails = agentDetails;
    }
    public Set getCustomerProducts() {
        return this.customerProducts;
    }
    
    public void setCustomerProducts(Set customerProducts) {
        this.customerProducts = customerProducts;
    }
    public Set getAccountCustomers() {
        return this.accountCustomers;
    }
    
    public void setAccountCustomers(Set accountCustomers) {
        this.accountCustomers = accountCustomers;
    }




}


