package com.commlink.agent.model;
// Generated Sep 18, 2019 4:58:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * District generated by hbm2java
 */
@Entity
@Table(name="DISTRICT"
    ,schema="AGENT"
)
public class District  implements java.io.Serializable {


     private int id;
     private Division division;
     private String nameEn;
     private String nameBn;
     private String code;
     private Set<Customer> customersForPresentDistrictId = new HashSet<Customer>(0);
     private Set<Customer> customersForPermanentDistrictId = new HashSet<Customer>(0);
     private Set<Upazila> upazilas = new HashSet<Upazila>(0);
     private Set<TempCustomer> tempCustomersForPermanentDistrictId = new HashSet<TempCustomer>(0);
     private Set<TempCustomer> tempCustomersForPresentDistrictId = new HashSet<TempCustomer>(0);

    public District() {
    }

	
    public District(int id, Division division, String nameEn, String nameBn, String code) {
        this.id = id;
        this.division = division;
        this.nameEn = nameEn;
        this.nameBn = nameBn;
        this.code = code;
    }
    public District(int id, Division division, String nameEn, String nameBn, String code, Set<Customer> customersForPresentDistrictId, Set<Customer> customersForPermanentDistrictId, Set<Upazila> upazilas, Set<TempCustomer> tempCustomersForPermanentDistrictId, Set<TempCustomer> tempCustomersForPresentDistrictId) {
       this.id = id;
       this.division = division;
       this.nameEn = nameEn;
       this.nameBn = nameBn;
       this.code = code;
       this.customersForPresentDistrictId = customersForPresentDistrictId;
       this.customersForPermanentDistrictId = customersForPermanentDistrictId;
       this.upazilas = upazilas;
       this.tempCustomersForPermanentDistrictId = tempCustomersForPermanentDistrictId;
       this.tempCustomersForPresentDistrictId = tempCustomersForPresentDistrictId;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=8, scale=0)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DIVISION_ID", nullable=false)
    public Division getDivision() {
        return this.division;
    }
    
    public void setDivision(Division division) {
        this.division = division;
    }

    
    @Column(name="NAME_EN", nullable=false, length=100)
    public String getNameEn() {
        return this.nameEn;
    }
    
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    
    @Column(name="NAME_BN", nullable=false, length=100)
    public String getNameBn() {
        return this.nameBn;
    }
    
    public void setNameBn(String nameBn) {
        this.nameBn = nameBn;
    }

    
    @Column(name="CODE", nullable=false, length=20)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="districtByPresentDistrictId")
    public Set<Customer> getCustomersForPresentDistrictId() {
        return this.customersForPresentDistrictId;
    }
    
    public void setCustomersForPresentDistrictId(Set<Customer> customersForPresentDistrictId) {
        this.customersForPresentDistrictId = customersForPresentDistrictId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="districtByPermanentDistrictId")
    public Set<Customer> getCustomersForPermanentDistrictId() {
        return this.customersForPermanentDistrictId;
    }
    
    public void setCustomersForPermanentDistrictId(Set<Customer> customersForPermanentDistrictId) {
        this.customersForPermanentDistrictId = customersForPermanentDistrictId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="district")
    public Set<Upazila> getUpazilas() {
        return this.upazilas;
    }
    
    public void setUpazilas(Set<Upazila> upazilas) {
        this.upazilas = upazilas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="districtByPermanentDistrictId")
    public Set<TempCustomer> getTempCustomersForPermanentDistrictId() {
        return this.tempCustomersForPermanentDistrictId;
    }
    
    public void setTempCustomersForPermanentDistrictId(Set<TempCustomer> tempCustomersForPermanentDistrictId) {
        this.tempCustomersForPermanentDistrictId = tempCustomersForPermanentDistrictId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="districtByPresentDistrictId")
    public Set<TempCustomer> getTempCustomersForPresentDistrictId() {
        return this.tempCustomersForPresentDistrictId;
    }
    
    public void setTempCustomersForPresentDistrictId(Set<TempCustomer> tempCustomersForPresentDistrictId) {
        this.tempCustomersForPresentDistrictId = tempCustomersForPresentDistrictId;
    }




}


