package com.commlink.agent.model;
// Generated Sep 18, 2019 3:24:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Division generated by hbm2java
 */
public class Division  implements java.io.Serializable {


     private int id;
     private String nameEn;
     private String nameBn;
     private String code;
     private Set customersForPermanentDivisionId = new HashSet(0);
     private Set tempCustomersForPermanentDivisionId = new HashSet(0);
     private Set tempCustomersForPresentDivisionId = new HashSet(0);
     private Set customersForPresentDivisionId = new HashSet(0);
     private Set districts = new HashSet(0);

    public Division() {
    }

	
    public Division(int id, String nameEn, String nameBn) {
        this.id = id;
        this.nameEn = nameEn;
        this.nameBn = nameBn;
    }
    public Division(int id, String nameEn, String nameBn, String code, Set customersForPermanentDivisionId, Set tempCustomersForPermanentDivisionId, Set tempCustomersForPresentDivisionId, Set customersForPresentDivisionId, Set districts) {
       this.id = id;
       this.nameEn = nameEn;
       this.nameBn = nameBn;
       this.code = code;
       this.customersForPermanentDivisionId = customersForPermanentDivisionId;
       this.tempCustomersForPermanentDivisionId = tempCustomersForPermanentDivisionId;
       this.tempCustomersForPresentDivisionId = tempCustomersForPresentDivisionId;
       this.customersForPresentDivisionId = customersForPresentDivisionId;
       this.districts = districts;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNameEn() {
        return this.nameEn;
    }
    
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }
    public String getNameBn() {
        return this.nameBn;
    }
    
    public void setNameBn(String nameBn) {
        this.nameBn = nameBn;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Set getCustomersForPermanentDivisionId() {
        return this.customersForPermanentDivisionId;
    }
    
    public void setCustomersForPermanentDivisionId(Set customersForPermanentDivisionId) {
        this.customersForPermanentDivisionId = customersForPermanentDivisionId;
    }
    public Set getTempCustomersForPermanentDivisionId() {
        return this.tempCustomersForPermanentDivisionId;
    }
    
    public void setTempCustomersForPermanentDivisionId(Set tempCustomersForPermanentDivisionId) {
        this.tempCustomersForPermanentDivisionId = tempCustomersForPermanentDivisionId;
    }
    public Set getTempCustomersForPresentDivisionId() {
        return this.tempCustomersForPresentDivisionId;
    }
    
    public void setTempCustomersForPresentDivisionId(Set tempCustomersForPresentDivisionId) {
        this.tempCustomersForPresentDivisionId = tempCustomersForPresentDivisionId;
    }
    public Set getCustomersForPresentDivisionId() {
        return this.customersForPresentDivisionId;
    }
    
    public void setCustomersForPresentDivisionId(Set customersForPresentDivisionId) {
        this.customersForPresentDivisionId = customersForPresentDivisionId;
    }
    public Set getDistricts() {
        return this.districts;
    }
    
    public void setDistricts(Set districts) {
        this.districts = districts;
    }




}


