package com.commlink.agent.model;
// Generated Sep 18, 2019 4:58:14 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ErrorLog generated by hbm2java
 */
@Entity
@Table(name="ERROR_LOG"
    ,schema="AGENT"
)
public class ErrorLog  implements java.io.Serializable {


     private BigDecimal id;
     private String title;
     private Clob info;
     private Date createdOn;
     private String createdBy;
     private Clob callstack;
     private Clob errorstack;
     private Clob errorbacktrace;

    public ErrorLog() {
    }

	
    public ErrorLog(BigDecimal id) {
        this.id = id;
    }
    public ErrorLog(BigDecimal id, String title, Clob info, Date createdOn, String createdBy, Clob callstack, Clob errorstack, Clob errorbacktrace) {
       this.id = id;
       this.title = title;
       this.info = info;
       this.createdOn = createdOn;
       this.createdBy = createdBy;
       this.callstack = callstack;
       this.errorstack = errorstack;
       this.errorbacktrace = errorbacktrace;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    
    @Column(name="TITLE", length=200)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="INFO")
    public Clob getInfo() {
        return this.info;
    }
    
    public void setInfo(Clob info) {
        this.info = info;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATED_ON", length=7)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="CREATED_BY", length=100)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="CALLSTACK")
    public Clob getCallstack() {
        return this.callstack;
    }
    
    public void setCallstack(Clob callstack) {
        this.callstack = callstack;
    }

    
    @Column(name="ERRORSTACK")
    public Clob getErrorstack() {
        return this.errorstack;
    }
    
    public void setErrorstack(Clob errorstack) {
        this.errorstack = errorstack;
    }

    
    @Column(name="ERRORBACKTRACE")
    public Clob getErrorbacktrace() {
        return this.errorbacktrace;
    }
    
    public void setErrorbacktrace(Clob errorbacktrace) {
        this.errorbacktrace = errorbacktrace;
    }




}


