package com.commlink.agent.model;
// Generated Sep 18, 2019 3:24:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Outlet generated by hbm2java
 */
public class Outlet  implements java.io.Serializable {


     private int id;
     private Branch branch;
     private String name;
     private Date openedOn;
     private String address;
     private String city;
     private boolean isDeleted;
     private String createdBy;
     private Date creationDate;
     private String modifiedBy;
     private Date modificationDate;
     private Set userInfos = new HashSet(0);

    public Outlet() {
    }

	
    public Outlet(int id, Branch branch, String name, String address, boolean isDeleted) {
        this.id = id;
        this.branch = branch;
        this.name = name;
        this.address = address;
        this.isDeleted = isDeleted;
    }
    public Outlet(int id, Branch branch, String name, Date openedOn, String address, String city, boolean isDeleted, String createdBy, Date creationDate, String modifiedBy, Date modificationDate, Set userInfos) {
       this.id = id;
       this.branch = branch;
       this.name = name;
       this.openedOn = openedOn;
       this.address = address;
       this.city = city;
       this.isDeleted = isDeleted;
       this.createdBy = createdBy;
       this.creationDate = creationDate;
       this.modifiedBy = modifiedBy;
       this.modificationDate = modificationDate;
       this.userInfos = userInfos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Branch getBranch() {
        return this.branch;
    }
    
    public void setBranch(Branch branch) {
        this.branch = branch;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getOpenedOn() {
        return this.openedOn;
    }
    
    public void setOpenedOn(Date openedOn) {
        this.openedOn = openedOn;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }
    public Set getUserInfos() {
        return this.userInfos;
    }
    
    public void setUserInfos(Set userInfos) {
        this.userInfos = userInfos;
    }




}


