package com.commlink.agent.model;
// Generated Sep 18, 2019 3:24:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Page generated by hbm2java
 */
public class Page  implements java.io.Serializable {


     private int id;
     private Page page;
     private String name;
     private String url;
     private Integer type;
     private String nameBangla;
     private Set rolePages = new HashSet(0);
     private Set pages = new HashSet(0);

    public Page() {
    }

	
    public Page(int id) {
        this.id = id;
    }
    public Page(int id, Page page, String name, String url, Integer type, String nameBangla, Set rolePages, Set pages) {
       this.id = id;
       this.page = page;
       this.name = name;
       this.url = url;
       this.type = type;
       this.nameBangla = nameBangla;
       this.rolePages = rolePages;
       this.pages = pages;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Page getPage() {
        return this.page;
    }
    
    public void setPage(Page page) {
        this.page = page;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public String getNameBangla() {
        return this.nameBangla;
    }
    
    public void setNameBangla(String nameBangla) {
        this.nameBangla = nameBangla;
    }
    public Set getRolePages() {
        return this.rolePages;
    }
    
    public void setRolePages(Set rolePages) {
        this.rolePages = rolePages;
    }
    public Set getPages() {
        return this.pages;
    }
    
    public void setPages(Set pages) {
        this.pages = pages;
    }




}


