package com.commlink.agent.model;
// Generated Sep 18, 2019 3:24:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private int id;
     private String name;
     private String minLimit;
     private Boolean isRecurring;
     private Date launchAt;
     private Integer type;
     private Boolean isDeleted;
     private String createdBy;
     private Date creationDate;
     private String modifiedBy;
     private Date modificationDate;
     private String code;
     private Short capPeriodDr;
     private Short capPeriodCr;
     private Short status;
     private String maxLimit;
     private Set tempCustomerProducts = new HashSet(0);
     private Set accounts = new HashSet(0);
     private Set customerProducts = new HashSet(0);

    public Product() {
    }

	
    public Product(int id, String name, String code) {
        this.id = id;
        this.name = name;
        this.code = code;
    }
    public Product(int id, String name, String minLimit, Boolean isRecurring, Date launchAt, Integer type, Boolean isDeleted, String createdBy, Date creationDate, String modifiedBy, Date modificationDate, String code, Short capPeriodDr, Short capPeriodCr, Short status, String maxLimit, Set tempCustomerProducts, Set accounts, Set customerProducts) {
       this.id = id;
       this.name = name;
       this.minLimit = minLimit;
       this.isRecurring = isRecurring;
       this.launchAt = launchAt;
       this.type = type;
       this.isDeleted = isDeleted;
       this.createdBy = createdBy;
       this.creationDate = creationDate;
       this.modifiedBy = modifiedBy;
       this.modificationDate = modificationDate;
       this.code = code;
       this.capPeriodDr = capPeriodDr;
       this.capPeriodCr = capPeriodCr;
       this.status = status;
       this.maxLimit = maxLimit;
       this.tempCustomerProducts = tempCustomerProducts;
       this.accounts = accounts;
       this.customerProducts = customerProducts;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getMinLimit() {
        return this.minLimit;
    }
    
    public void setMinLimit(String minLimit) {
        this.minLimit = minLimit;
    }
    public Boolean getIsRecurring() {
        return this.isRecurring;
    }
    
    public void setIsRecurring(Boolean isRecurring) {
        this.isRecurring = isRecurring;
    }
    public Date getLaunchAt() {
        return this.launchAt;
    }
    
    public void setLaunchAt(Date launchAt) {
        this.launchAt = launchAt;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Short getCapPeriodDr() {
        return this.capPeriodDr;
    }
    
    public void setCapPeriodDr(Short capPeriodDr) {
        this.capPeriodDr = capPeriodDr;
    }
    public Short getCapPeriodCr() {
        return this.capPeriodCr;
    }
    
    public void setCapPeriodCr(Short capPeriodCr) {
        this.capPeriodCr = capPeriodCr;
    }
    public Short getStatus() {
        return this.status;
    }
    
    public void setStatus(Short status) {
        this.status = status;
    }
    public String getMaxLimit() {
        return this.maxLimit;
    }
    
    public void setMaxLimit(String maxLimit) {
        this.maxLimit = maxLimit;
    }
    public Set getTempCustomerProducts() {
        return this.tempCustomerProducts;
    }
    
    public void setTempCustomerProducts(Set tempCustomerProducts) {
        this.tempCustomerProducts = tempCustomerProducts;
    }
    public Set getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set accounts) {
        this.accounts = accounts;
    }
    public Set getCustomerProducts() {
        return this.customerProducts;
    }
    
    public void setCustomerProducts(Set customerProducts) {
        this.customerProducts = customerProducts;
    }




}


