package com.commlink.agent.model;
// Generated Sep 25, 2019 11:25:45 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Range generated by hbm2java
 */
@Entity
@Table(name="RANGE"
    ,schema="AGENT"
)
public class Range  implements java.io.Serializable {


     private int id;
     private Long upperLimit;
     private String createdBy;
     private Date creationDate;
     private String modifiedBy;
     private Date modifiedDate;
     private Set<Commission> commissions = new HashSet<Commission>(0);

    public Range() {
    }

	
    public Range(int id) {
        this.id = id;
    }
    public Range(int id, Long upperLimit, String createdBy, Date creationDate, String modifiedBy, Date modifiedDate, Set<Commission> commissions) {
       this.id = id;
       this.upperLimit = upperLimit;
       this.createdBy = createdBy;
       this.creationDate = creationDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.commissions = commissions;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=8, scale=0)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="UPPER_LIMIT", precision=10, scale=0)
    public Long getUpperLimit() {
        return this.upperLimit;
    }
    
    public void setUpperLimit(Long upperLimit) {
        this.upperLimit = upperLimit;
    }

    
    @Column(name="CREATED_BY", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATION_DATE")
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    
    @Column(name="MODIFIED_BY", length=20)
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MODIFIED_DATE")
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="range")
    public Set<Commission> getCommissions() {
        return this.commissions;
    }
    
    public void setCommissions(Set<Commission> commissions) {
        this.commissions = commissions;
    }




}


