package com.commlink.agent.model;
// Generated Sep 18, 2019 3:24:34 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * RolePage generated by hbm2java
 */
public class RolePage  implements java.io.Serializable {


     private BigDecimal id;
     private Role role;
     private Page page;

    public RolePage() {
    }

    public RolePage(BigDecimal id, Role role, Page page) {
       this.id = id;
       this.role = role;
       this.page = page;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public Page getPage() {
        return this.page;
    }
    
    public void setPage(Page page) {
        this.page = page;
    }




}


