package com.commlink.agent.model;
// Generated Sep 18, 2019 4:58:14 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Settings generated by hbm2java
 */
@Entity
@Table(name="SETTINGS"
    ,schema="AGENT"
)
public class Settings  implements java.io.Serializable {


     private int id;
     private String key;
     private String value;

    public Settings() {
    }

	
    public Settings(int id) {
        this.id = id;
    }
    public Settings(int id, String key, String value) {
       this.id = id;
       this.key = key;
       this.value = value;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=8, scale=0)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="KEY", length=50)
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }

    
    @Column(name="VALUE", length=50)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


