package com.commlink.agent.model;
// Generated Sep 18, 2019 3:24:34 PM by Hibernate Tools 4.3.1



/**
 * Settings generated by hbm2java
 */
public class Settings  implements java.io.Serializable {


     private int id;
     private String key;
     private String value;

    public Settings() {
    }

	
    public Settings(int id) {
        this.id = id;
    }
    public Settings(int id, String key, String value) {
       this.id = id;
       this.key = key;
       this.value = value;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


