package com.commlink.agent.model;
// Generated Sep 18, 2019 3:24:34 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Tax generated by hbm2java
 */
public class Tax  implements java.io.Serializable {


     private int id;
     private BigDecimal rate;
     private Boolean hasTin;
     private Integer interval;
     private boolean isDeleted;
     private String createdBy;
     private Date creationDate;
     private String modifiedBy;
     private Date modificationDate;

    public Tax() {
    }

	
    public Tax(int id, boolean isDeleted) {
        this.id = id;
        this.isDeleted = isDeleted;
    }
    public Tax(int id, BigDecimal rate, Boolean hasTin, Integer interval, boolean isDeleted, String createdBy, Date creationDate, String modifiedBy, Date modificationDate) {
       this.id = id;
       this.rate = rate;
       this.hasTin = hasTin;
       this.interval = interval;
       this.isDeleted = isDeleted;
       this.createdBy = createdBy;
       this.creationDate = creationDate;
       this.modifiedBy = modifiedBy;
       this.modificationDate = modificationDate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public BigDecimal getRate() {
        return this.rate;
    }
    
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }
    public Boolean getHasTin() {
        return this.hasTin;
    }
    
    public void setHasTin(Boolean hasTin) {
        this.hasTin = hasTin;
    }
    public Integer getInterval() {
        return this.interval;
    }
    
    public void setInterval(Integer interval) {
        this.interval = interval;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }




}


