package com.commlink.agent.model;
// Generated Sep 18, 2019 4:58:14 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TempCustomerProduct generated by hbm2java
 */
@Entity
@Table(name="TEMP_CUSTOMER_PRODUCT"
    ,schema="AGENT"
)
public class TempCustomerProduct  implements java.io.Serializable {


     private int id;
     private Product product;
     private TempCustomer tempCustomer;
     private Short type;
     private Date dateTime;
     private Integer status;

    public TempCustomerProduct() {
    }

	
    public TempCustomerProduct(int id) {
        this.id = id;
    }
    public TempCustomerProduct(int id, Product product, TempCustomer tempCustomer, Short type, Date dateTime, Integer status) {
       this.id = id;
       this.product = product;
       this.tempCustomer = tempCustomer;
       this.type = type;
       this.dateTime = dateTime;
       this.status = status;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=8, scale=0)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUCT_ID")
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CUSTOMER_ID")
    public TempCustomer getTempCustomer() {
        return this.tempCustomer;
    }
    
    public void setTempCustomer(TempCustomer tempCustomer) {
        this.tempCustomer = tempCustomer;
    }

    
    @Column(name="TYPE", precision=4, scale=0)
    public Short getType() {
        return this.type;
    }
    
    public void setType(Short type) {
        this.type = type;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE_TIME")
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }

    
    @Column(name="STATUS", precision=8, scale=0)
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


