package com.commlink.agent.model;
// Generated Sep 18, 2019 3:24:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TempCustomerProduct generated by hbm2java
 */
public class TempCustomerProduct  implements java.io.Serializable {


     private int id;
     private Product product;
     private TempCustomer tempCustomer;
     private Short type;
     private Date dateTime;
     private Integer status;

    public TempCustomerProduct() {
    }

	
    public TempCustomerProduct(int id) {
        this.id = id;
    }
    public TempCustomerProduct(int id, Product product, TempCustomer tempCustomer, Short type, Date dateTime, Integer status) {
       this.id = id;
       this.product = product;
       this.tempCustomer = tempCustomer;
       this.type = type;
       this.dateTime = dateTime;
       this.status = status;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public TempCustomer getTempCustomer() {
        return this.tempCustomer;
    }
    
    public void setTempCustomer(TempCustomer tempCustomer) {
        this.tempCustomer = tempCustomer;
    }
    public Short getType() {
        return this.type;
    }
    
    public void setType(Short type) {
        this.type = type;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


