package com.commlink.agent.model;
// Generated Sep 18, 2019 3:24:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TransactionType generated by hbm2java
 */
public class TransactionType  implements java.io.Serializable {


     private short code;
     private int id;
     private boolean isDeleted;
     private String createdBy;
     private Date creationDate;
     private Date modificationDate;
     private String modifiedBy;
     private String name;
     private Short multipleDebitEntries;
     private Short multipleCreditEntries;
     private Set commissions = new HashSet(0);
     private Set transactions = new HashSet(0);

    public TransactionType() {
    }

	
    public TransactionType(short code, int id, boolean isDeleted) {
        this.code = code;
        this.id = id;
        this.isDeleted = isDeleted;
    }
    public TransactionType(short code, int id, boolean isDeleted, String createdBy, Date creationDate, Date modificationDate, String modifiedBy, String name, Short multipleDebitEntries, Short multipleCreditEntries, Set commissions, Set transactions) {
       this.code = code;
       this.id = id;
       this.isDeleted = isDeleted;
       this.createdBy = createdBy;
       this.creationDate = creationDate;
       this.modificationDate = modificationDate;
       this.modifiedBy = modifiedBy;
       this.name = name;
       this.multipleDebitEntries = multipleDebitEntries;
       this.multipleCreditEntries = multipleCreditEntries;
       this.commissions = commissions;
       this.transactions = transactions;
    }
   
    public short getCode() {
        return this.code;
    }
    
    public void setCode(short code) {
        this.code = code;
    }
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Date getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Short getMultipleDebitEntries() {
        return this.multipleDebitEntries;
    }
    
    public void setMultipleDebitEntries(Short multipleDebitEntries) {
        this.multipleDebitEntries = multipleDebitEntries;
    }
    public Short getMultipleCreditEntries() {
        return this.multipleCreditEntries;
    }
    
    public void setMultipleCreditEntries(Short multipleCreditEntries) {
        this.multipleCreditEntries = multipleCreditEntries;
    }
    public Set getCommissions() {
        return this.commissions;
    }
    
    public void setCommissions(Set commissions) {
        this.commissions = commissions;
    }
    public Set getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set transactions) {
        this.transactions = transactions;
    }




}


