package com.commlink.agent.model;
// Generated Sep 18, 2019 3:24:34 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transaction generated by hbm2java
 */
public class Transaction  implements java.io.Serializable {


     private int id;
     private Account accountBySrcAccId;
     private Account accountByAgentAccId;
     private Account accountByDestAccId;
     private TransactionType transactionType;
     private Transaction transaction;
     private boolean isDeleted;
     private String createdBy;
     private Date creationDate;
     private Date modificationDate;
     private String modifiedBy;
     private BigDecimal amount;
     private String description;
     private Boolean isReversed;
     private Short status;
     private Date transactionDate;
     private Set transactionDetails = new HashSet(0);
     private Set transactions = new HashSet(0);

    public Transaction() {
    }

	
    public Transaction(int id, boolean isDeleted) {
        this.id = id;
        this.isDeleted = isDeleted;
    }
    public Transaction(int id, Account accountBySrcAccId, Account accountByAgentAccId, Account accountByDestAccId, TransactionType transactionType, Transaction transaction, boolean isDeleted, String createdBy, Date creationDate, Date modificationDate, String modifiedBy, BigDecimal amount, String description, Boolean isReversed, Short status, Date transactionDate, Set transactionDetails, Set transactions) {
       this.id = id;
       this.accountBySrcAccId = accountBySrcAccId;
       this.accountByAgentAccId = accountByAgentAccId;
       this.accountByDestAccId = accountByDestAccId;
       this.transactionType = transactionType;
       this.transaction = transaction;
       this.isDeleted = isDeleted;
       this.createdBy = createdBy;
       this.creationDate = creationDate;
       this.modificationDate = modificationDate;
       this.modifiedBy = modifiedBy;
       this.amount = amount;
       this.description = description;
       this.isReversed = isReversed;
       this.status = status;
       this.transactionDate = transactionDate;
       this.transactionDetails = transactionDetails;
       this.transactions = transactions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Account getAccountBySrcAccId() {
        return this.accountBySrcAccId;
    }
    
    public void setAccountBySrcAccId(Account accountBySrcAccId) {
        this.accountBySrcAccId = accountBySrcAccId;
    }
    public Account getAccountByAgentAccId() {
        return this.accountByAgentAccId;
    }
    
    public void setAccountByAgentAccId(Account accountByAgentAccId) {
        this.accountByAgentAccId = accountByAgentAccId;
    }
    public Account getAccountByDestAccId() {
        return this.accountByDestAccId;
    }
    
    public void setAccountByDestAccId(Account accountByDestAccId) {
        this.accountByDestAccId = accountByDestAccId;
    }
    public TransactionType getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(TransactionType transactionType) {
        this.transactionType = transactionType;
    }
    public Transaction getTransaction() {
        return this.transaction;
    }
    
    public void setTransaction(Transaction transaction) {
        this.transaction = transaction;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Date getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Boolean getIsReversed() {
        return this.isReversed;
    }
    
    public void setIsReversed(Boolean isReversed) {
        this.isReversed = isReversed;
    }
    public Short getStatus() {
        return this.status;
    }
    
    public void setStatus(Short status) {
        this.status = status;
    }
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }
    public Set getTransactionDetails() {
        return this.transactionDetails;
    }
    
    public void setTransactionDetails(Set transactionDetails) {
        this.transactionDetails = transactionDetails;
    }
    public Set getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set transactions) {
        this.transactions = transactions;
    }




}


