package com.commlink.agent.model;
// Generated Sep 18, 2019 3:24:34 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * TransactionDetail generated by hbm2java
 */
public class TransactionDetail  implements java.io.Serializable {


     private int id;
     private Account account;
     private Transaction transaction;
     private boolean isDeleted;
     private String createdBy;
     private Date creationDate;
     private Date modificationDate;
     private String modifiedBy;
     private Integer debitAmount;
     private String creditAmount;
     private String description;
     private BigDecimal runningBalance;

    public TransactionDetail() {
    }

	
    public TransactionDetail(int id, boolean isDeleted) {
        this.id = id;
        this.isDeleted = isDeleted;
    }
    public TransactionDetail(int id, Account account, Transaction transaction, boolean isDeleted, String createdBy, Date creationDate, Date modificationDate, String modifiedBy, Integer debitAmount, String creditAmount, String description, BigDecimal runningBalance) {
       this.id = id;
       this.account = account;
       this.transaction = transaction;
       this.isDeleted = isDeleted;
       this.createdBy = createdBy;
       this.creationDate = creationDate;
       this.modificationDate = modificationDate;
       this.modifiedBy = modifiedBy;
       this.debitAmount = debitAmount;
       this.creditAmount = creditAmount;
       this.description = description;
       this.runningBalance = runningBalance;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Transaction getTransaction() {
        return this.transaction;
    }
    
    public void setTransaction(Transaction transaction) {
        this.transaction = transaction;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Date getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Integer getDebitAmount() {
        return this.debitAmount;
    }
    
    public void setDebitAmount(Integer debitAmount) {
        this.debitAmount = debitAmount;
    }
    public String getCreditAmount() {
        return this.creditAmount;
    }
    
    public void setCreditAmount(String creditAmount) {
        this.creditAmount = creditAmount;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getRunningBalance() {
        return this.runningBalance;
    }
    
    public void setRunningBalance(BigDecimal runningBalance) {
        this.runningBalance = runningBalance;
    }




}


