package com.commlink.agent.model;
// Generated Sep 18, 2019 4:58:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Upazila generated by hbm2java
 */
@Entity
@Table(name="UPAZILA"
    ,schema="AGENT"
)
public class Upazila  implements java.io.Serializable {


     private int id;
     private District district;
     private String nameEn;
     private String nameBn;
     private String code;
     private Set<Customer> customersForPresentUpazilaId = new HashSet<Customer>(0);
     private Set<Customer> customersForPermanentUpazilaId = new HashSet<Customer>(0);
     private Set<TempCustomer> tempCustomersForPermanentUpazilaId = new HashSet<TempCustomer>(0);
     private Set<TempCustomer> tempCustomersForPresentUpazilaId = new HashSet<TempCustomer>(0);

    public Upazila() {
    }

	
    public Upazila(int id, District district, String nameEn, String nameBn) {
        this.id = id;
        this.district = district;
        this.nameEn = nameEn;
        this.nameBn = nameBn;
    }
    public Upazila(int id, District district, String nameEn, String nameBn, String code, Set<Customer> customersForPresentUpazilaId, Set<Customer> customersForPermanentUpazilaId, Set<TempCustomer> tempCustomersForPermanentUpazilaId, Set<TempCustomer> tempCustomersForPresentUpazilaId) {
       this.id = id;
       this.district = district;
       this.nameEn = nameEn;
       this.nameBn = nameBn;
       this.code = code;
       this.customersForPresentUpazilaId = customersForPresentUpazilaId;
       this.customersForPermanentUpazilaId = customersForPermanentUpazilaId;
       this.tempCustomersForPermanentUpazilaId = tempCustomersForPermanentUpazilaId;
       this.tempCustomersForPresentUpazilaId = tempCustomersForPresentUpazilaId;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=8, scale=0)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DISTRICT_ID", nullable=false)
    public District getDistrict() {
        return this.district;
    }
    
    public void setDistrict(District district) {
        this.district = district;
    }

    
    @Column(name="NAME_EN", nullable=false, length=100)
    public String getNameEn() {
        return this.nameEn;
    }
    
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    
    @Column(name="NAME_BN", nullable=false, length=100)
    public String getNameBn() {
        return this.nameBn;
    }
    
    public void setNameBn(String nameBn) {
        this.nameBn = nameBn;
    }

    
    @Column(name="CODE", length=20)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="upazilaByPresentUpazilaId")
    public Set<Customer> getCustomersForPresentUpazilaId() {
        return this.customersForPresentUpazilaId;
    }
    
    public void setCustomersForPresentUpazilaId(Set<Customer> customersForPresentUpazilaId) {
        this.customersForPresentUpazilaId = customersForPresentUpazilaId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="upazilaByPermanentUpazilaId")
    public Set<Customer> getCustomersForPermanentUpazilaId() {
        return this.customersForPermanentUpazilaId;
    }
    
    public void setCustomersForPermanentUpazilaId(Set<Customer> customersForPermanentUpazilaId) {
        this.customersForPermanentUpazilaId = customersForPermanentUpazilaId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="upazilaByPermanentUpazilaId")
    public Set<TempCustomer> getTempCustomersForPermanentUpazilaId() {
        return this.tempCustomersForPermanentUpazilaId;
    }
    
    public void setTempCustomersForPermanentUpazilaId(Set<TempCustomer> tempCustomersForPermanentUpazilaId) {
        this.tempCustomersForPermanentUpazilaId = tempCustomersForPermanentUpazilaId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="upazilaByPresentUpazilaId")
    public Set<TempCustomer> getTempCustomersForPresentUpazilaId() {
        return this.tempCustomersForPresentUpazilaId;
    }
    
    public void setTempCustomersForPresentUpazilaId(Set<TempCustomer> tempCustomersForPresentUpazilaId) {
        this.tempCustomersForPresentUpazilaId = tempCustomersForPresentUpazilaId;
    }




}


