package com.commlink.agent.model;
// Generated Sep 18, 2019 3:24:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Upazila generated by hbm2java
 */
public class Upazila  implements java.io.Serializable {


     private int id;
     private District district;
     private String nameEn;
     private String nameBn;
     private String code;
     private Set customersForPresentUpazilaId = new HashSet(0);
     private Set customersForPermanentUpazilaId = new HashSet(0);
     private Set tempCustomersForPermanentUpazilaId = new HashSet(0);
     private Set tempCustomersForPresentUpazilaId = new HashSet(0);

    public Upazila() {
    }

	
    public Upazila(int id, District district, String nameEn, String nameBn) {
        this.id = id;
        this.district = district;
        this.nameEn = nameEn;
        this.nameBn = nameBn;
    }
    public Upazila(int id, District district, String nameEn, String nameBn, String code, Set customersForPresentUpazilaId, Set customersForPermanentUpazilaId, Set tempCustomersForPermanentUpazilaId, Set tempCustomersForPresentUpazilaId) {
       this.id = id;
       this.district = district;
       this.nameEn = nameEn;
       this.nameBn = nameBn;
       this.code = code;
       this.customersForPresentUpazilaId = customersForPresentUpazilaId;
       this.customersForPermanentUpazilaId = customersForPermanentUpazilaId;
       this.tempCustomersForPermanentUpazilaId = tempCustomersForPermanentUpazilaId;
       this.tempCustomersForPresentUpazilaId = tempCustomersForPresentUpazilaId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public District getDistrict() {
        return this.district;
    }
    
    public void setDistrict(District district) {
        this.district = district;
    }
    public String getNameEn() {
        return this.nameEn;
    }
    
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }
    public String getNameBn() {
        return this.nameBn;
    }
    
    public void setNameBn(String nameBn) {
        this.nameBn = nameBn;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Set getCustomersForPresentUpazilaId() {
        return this.customersForPresentUpazilaId;
    }
    
    public void setCustomersForPresentUpazilaId(Set customersForPresentUpazilaId) {
        this.customersForPresentUpazilaId = customersForPresentUpazilaId;
    }
    public Set getCustomersForPermanentUpazilaId() {
        return this.customersForPermanentUpazilaId;
    }
    
    public void setCustomersForPermanentUpazilaId(Set customersForPermanentUpazilaId) {
        this.customersForPermanentUpazilaId = customersForPermanentUpazilaId;
    }
    public Set getTempCustomersForPermanentUpazilaId() {
        return this.tempCustomersForPermanentUpazilaId;
    }
    
    public void setTempCustomersForPermanentUpazilaId(Set tempCustomersForPermanentUpazilaId) {
        this.tempCustomersForPermanentUpazilaId = tempCustomersForPermanentUpazilaId;
    }
    public Set getTempCustomersForPresentUpazilaId() {
        return this.tempCustomersForPresentUpazilaId;
    }
    
    public void setTempCustomersForPresentUpazilaId(Set tempCustomersForPresentUpazilaId) {
        this.tempCustomersForPresentUpazilaId = tempCustomersForPresentUpazilaId;
    }




}


