package com.commlink.agent.model;
// Generated Sep 18, 2019 3:24:34 PM by Hibernate Tools 4.3.1



/**
 * UserAccountMap generated by hbm2java
 */
public class UserAccountMap  implements java.io.Serializable {


     private int id;
     private Integer userId;
     private Integer accId;
     private Boolean isPrimary;

    public UserAccountMap() {
    }

	
    public UserAccountMap(int id) {
        this.id = id;
    }
    public UserAccountMap(int id, Integer userId, Integer accId, Boolean isPrimary) {
       this.id = id;
       this.userId = userId;
       this.accId = accId;
       this.isPrimary = isPrimary;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Integer getAccId() {
        return this.accId;
    }
    
    public void setAccId(Integer accId) {
        this.accId = accId;
    }
    public Boolean getIsPrimary() {
        return this.isPrimary;
    }
    
    public void setIsPrimary(Boolean isPrimary) {
        this.isPrimary = isPrimary;
    }




}


