package com.commlink.agent.model;
// Generated Sep 18, 2019 3:24:34 PM by Hibernate Tools 4.3.1


import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserInfo generated by hbm2java
 */
public class UserInfo  implements java.io.Serializable {


     private int id;
     private UserInfo userInfo;
     private Role role;
     private Customer customer;
     private Outlet outlet;
     private String userName;
     private String passwordHash;
     private String pin;
     private boolean isDeleted;
     private String createdBy;
     private Date creationDate;
     private String modifiedBy;
     private Date modificationDate;
     private Blob fingerprint;
     private int authType;
     private Short type;
     private Integer status;
     private Set userInfos = new HashSet(0);

    public UserInfo() {
    }

	
    public UserInfo(int id, String userName, String pin, boolean isDeleted, int authType) {
        this.id = id;
        this.userName = userName;
        this.pin = pin;
        this.isDeleted = isDeleted;
        this.authType = authType;
    }
    public UserInfo(int id, UserInfo userInfo, Role role, Customer customer, Outlet outlet, String userName, String passwordHash, String pin, boolean isDeleted, String createdBy, Date creationDate, String modifiedBy, Date modificationDate, Blob fingerprint, int authType, Short type, Integer status, Set userInfos) {
       this.id = id;
       this.userInfo = userInfo;
       this.role = role;
       this.customer = customer;
       this.outlet = outlet;
       this.userName = userName;
       this.passwordHash = passwordHash;
       this.pin = pin;
       this.isDeleted = isDeleted;
       this.createdBy = createdBy;
       this.creationDate = creationDate;
       this.modifiedBy = modifiedBy;
       this.modificationDate = modificationDate;
       this.fingerprint = fingerprint;
       this.authType = authType;
       this.type = type;
       this.status = status;
       this.userInfos = userInfos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Outlet getOutlet() {
        return this.outlet;
    }
    
    public void setOutlet(Outlet outlet) {
        this.outlet = outlet;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPasswordHash() {
        return this.passwordHash;
    }
    
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }
    public String getPin() {
        return this.pin;
    }
    
    public void setPin(String pin) {
        this.pin = pin;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModificationDate() {
        return this.modificationDate;
    }
    
    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }
    public Blob getFingerprint() {
        return this.fingerprint;
    }
    
    public void setFingerprint(Blob fingerprint) {
        this.fingerprint = fingerprint;
    }
    public int getAuthType() {
        return this.authType;
    }
    
    public void setAuthType(int authType) {
        this.authType = authType;
    }
    public Short getType() {
        return this.type;
    }
    
    public void setType(Short type) {
        this.type = type;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getUserInfos() {
        return this.userInfos;
    }
    
    public void setUserInfos(Set userInfos) {
        this.userInfos = userInfos;
    }




}


